name: Android CI

on:
  push:
    branches:
      - snapshot
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Generate release notes
        run: ./gradlew -q getChangelog >> RELEASE_NOTES.md

      - name: Release on Github
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_NAME }}
          body_path: RELEASE_NOTES.md
          files: |
            socket-server/build/outputs/aar/socket-client-release.aar
            socket-client/build/outputs/aar/socket-client-release.aar

      - name: Release to sonatype
        run: ./gradlew publish --no-daemon --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
